//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DAKObligatorioEntities : DbContext
    {
        public DAKObligatorioEntities()
            : base("name=DAKObligatorioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Camion> T_Camion { get; set; }
        public virtual DbSet<T_Camion_Zona> T_Camion_Zona { get; set; }
        public virtual DbSet<T_Cliente> T_Cliente { get; set; }
        public virtual DbSet<T_Direccion> T_Direccion { get; set; }
        public virtual DbSet<T_Empresa> T_Empresa { get; set; }
        public virtual DbSet<T_Envio> T_Envio { get; set; }
        public virtual DbSet<T_Funcionario> T_Funcionario { get; set; }
        public virtual DbSet<T_GrupoPrecio> T_GrupoPrecio { get; set; }
        public virtual DbSet<T_Persona> T_Persona { get; set; }
        public virtual DbSet<T_Puntos_Zona> T_Puntos_Zona { get; set; }
        public virtual DbSet<T_Ruta> T_Ruta { get; set; }
        public virtual DbSet<T_Ruta_Direcciones> T_Ruta_Direcciones { get; set; }
        public virtual DbSet<T_TipoPago> T_TipoPago { get; set; }
        public virtual DbSet<T_Zona> T_Zona { get; set; }
    }
}
