//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Ruta_Direcciones
    {
        public long ID { get; set; }
        public long IDRuta { get; set; }
        public long IDDireccion { get; set; }
    
        public virtual T_Direccion T_Direccion { get; set; }
        public virtual T_Ruta T_Ruta { get; set; }
    }
}
